### Laptops Data

In [ ]:
import selenium 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

## -- Options --
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")


## -- Laptops List --
Lap = []

## -- Scrapping --
driver = webdriver.Chrome(options=options)
driver.get("https://www.amazon.eg/-/en/b?node=21832907031&ref_=GSNavPC_6&pf_rd_r=1SBAN226ER89HY3P4QP1&pf_rd_p=2ebd2917-3f3c-4181-96bf-b831abfe4d2b&pf_rd_m=A1ZVRGNO5AYLOV&pf_rd_s=merchandised-search-4&pf_rd_t=&pf_rd_i=18018102031")
time.sleep(5)

## -- Accept Cookies --
try:
    WebDriverWait(driver, 5).until(
        EC.element_to_be_clickable((By.ID, "sp-cc-accept"))
    ).click()
except TimeoutException:
    pass 
driver.find_element(By.ID, 'apb-desktop-browse-search-see-all').click()
time.sleep(5)
page = 1

while True:

    cards = driver.find_elements(By.CSS_SELECTOR,'div[data-component-type="s-search-result"]')
    page_products = 0

    for card in cards:

        try:
            Name = card.find_element(By.CSS_SELECTOR, 'h2').get_attribute('aria-label')
            Link = card.find_element(By.CSS_SELECTOR, 'a.a-link-normal[href*="/dp/"]').get_attribute('href')
            Image = card.find_element(By.CSS_SELECTOR, 'img.s-image').get_attribute('src')

        except NoSuchElementException:
            continue

        try:
            Rating = card.find_element(By.CSS_SELECTOR,'[data-cy="reviews-block"] span.a-size-small.a-color-base').text

        except NoSuchElementException:
            Rating = "Not Available"

        try:
            Reviews = card.find_element(By.CSS_SELECTOR,'[data-cy="reviews-block"] a[aria-label$="ratings"]').get_attribute('aria-label')

        except NoSuchElementException:
            Reviews = "Not Available"

        try:
            Price = card.find_element(By.CLASS_NAME, 'a-price-whole').text

        except NoSuchElementException:
            Price = "Product Not Available"

        Lap.append({
            'Name': Name,
            'Link': Link,
            'Image': Image,
            'Rating': Rating,
            'Reviews': Reviews,
            'Price': Price
        })

        page_products += 1

    print(
        f"Page {page} finished successfully. "
        f"Products collected on this page: {page_products}. "
        f"Total products collected: {len(Lap)}"
    )

    try:
        next_page = driver.find_element(By.CSS_SELECTOR,'a.s-pagination-next')

        if 's-pagination-disabled' in next_page.get_attribute('class'):
            print("Scraping finished. No more pages available.")
            break

        next_page.click()
        page += 1
        time.sleep(5)

    except NoSuchElementException:
        print("Next page button not found. Check the pagination selector.")
        break

In [24]:
import pandas as pd 

df_Laptops = pd.DataFrame(Lap)

In [25]:
df_Laptops.head()

,Name,Link,Image,Rating,Reviews,Price
0,ASUS TUF Gaming F16 [FX607VJB-RL805W] Core 5-2...,https://www.amazon.eg/-/en/ASUS-FX607VJB-RL805...,https://m.media-amazon.com/images/I/51ug5icR5+...,5.0,1 ratings,"47,999"
1,"HP Laptop AI 15-fd2001ne Ultra 7-255U, 16GB Ra...",https://www.amazon.eg/-/en/HP-15-fd2001ne-Grap...,https://m.media-amazon.com/images/I/51Ih6Iavyd...,4.7,6 ratings,"47,777"
2,Lenovo Legion 5 15IRX10 Gaming Laptop Intel Co...,https://www.amazon.eg/-/en/Lenovo-15IRX10-i7-1...,https://m.media-amazon.com/images/I/71jvNSQ5HG...,1.0,2 ratings,"82,999"
3,"Lenovo LOQ 15IAX9 Gaming Laptop, Intel Core i5...",https://www.amazon.eg/-/en/Lenovo-15IAX9-13450...,https://m.media-amazon.com/images/I/61ZxvicMqD...,3.6,3 ratings,"66,009"
4,"Apple 2025 MacBook Air (13-inch, Apple M4 chip...",https://www.amazon.eg/-/en/Apple-MacBook-13-in...,https://m.media-amazon.com/images/I/71ruYxfXRy...,Not Available,Not Available,"81,903"

In [26]:
df_Laptops.to_csv("Laptops.csv" , index = False )
df_Laptops.to_parquet("Laptops.parquet" , index = False )

### PCs

In [ ]:
import selenium 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

## -- Options --
options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")


## -- Laptops List --
PC = []

## -- Scrapping --
driver = webdriver.Chrome(options=options)
driver.get("https://www.amazon.eg/-/en/b?node=21832872031&ref_=GSNavPC_3&pf_rd_r=1SBAN226ER89HY3P4QP1&pf_rd_p=2ebd2917-3f3c-4181-96bf-b831abfe4d2b&pf_rd_m=A1ZVRGNO5AYLOV&pf_rd_s=merchandised-search-4&pf_rd_t=&pf_rd_i=18018102031")
time.sleep(5)

## -- Accept Cookies --
try:
    WebDriverWait(driver, 5).until(
        EC.element_to_be_clickable((By.ID, "sp-cc-accept"))
    ).click()
except TimeoutException:
    pass 
driver.find_element(By.ID, 'apb-desktop-browse-search-see-all').click()
time.sleep(5)
page = 1

while True:

    cards = driver.find_elements(By.CSS_SELECTOR,'div[data-component-type="s-search-result"]')
    page_products = 0

    for card in cards:

        try:
            Name = card.find_element(By.CSS_SELECTOR, 'h2').get_attribute('aria-label')
            Link = card.find_element(By.CSS_SELECTOR, 'a.a-link-normal[href*="/dp/"]').get_attribute('href')
            Image = card.find_element(By.CSS_SELECTOR, 'img.s-image').get_attribute('src')

        except NoSuchElementException:
            continue

        try:
            Rating = card.find_element(By.CSS_SELECTOR,'[data-cy="reviews-block"] span.a-size-small.a-color-base').text

        except NoSuchElementException:
            Rating = "Not Available"

        try:
            Reviews = card.find_element(By.CSS_SELECTOR,'[data-cy="reviews-block"] a[aria-label$="ratings"]').get_attribute('aria-label')

        except NoSuchElementException:
            Reviews = "Not Available"

        try:
            Price = card.find_element(By.CLASS_NAME, 'a-price-whole').text

        except NoSuchElementException:
            Price = "Product Not Available"

        PC.append({
            'Name': Name,
            'Link': Link,
            'Image': Image,
            'Rating': Rating,
            'Reviews': Reviews,
            'Price': Price
        })

        page_products += 1

    print(
        f"Page {page} finished successfully. "
        f"Products collected on this page: {page_products}. "
        f"Total products collected: {len(PC)}"
    )

    try:
        next_page = driver.find_element(By.CSS_SELECTOR,'a.s-pagination-next')

        if 's-pagination-disabled' in next_page.get_attribute('class'):
            print("Scraping finished. No more pages available.")
            break

        next_page.click()
        page += 1
        time.sleep(5)

    except NoSuchElementException:
        print("Next page button not found. Check the pagination selector.")
        break

In [28]:
df_PC = pd.DataFrame(PC)

In [30]:
df_PC.head()

,Name,Link,Image,Rating,Reviews,Price
0,"Adjustable laptop stand, portable aluminium la...",https://www.amazon.eg/-/en/Adjustable-portable...,https://m.media-amazon.com/images/I/61fRwSb0z0...,3.9,"7,993 ratings",93
1,"KANMABPC Wireless Bluetooth Mouse, Rechargeabl...",https://www.amazon.eg/-/en/KANMABPC-Wireless-B...,https://m.media-amazon.com/images/I/61aJwjV4Na...,4.0,"8,228 ratings",105
2,"Anker USB-C to USB-C 2.0 cable (3ft/0.9m), Hig...",https://www.amazon.eg/-/en/Anker-Durability-Ch...,https://m.media-amazon.com/images/I/51IZ24O2w5...,4.5,878 ratings,199
3,Kingston 64GB Exodia USB 3.20 Flash - DTX/64GB,https://www.amazon.eg/-/en/Kingston-64GB-Exodi...,https://m.media-amazon.com/images/I/414M-xDP8T...,4.2,"21,931 ratings",349
4,TP-Link 300MBPS TL-WA850RE Wi-Fi Range Extende...,https://www.amazon.eg/-/en/TP-Link-300MBPS-TL-...,https://m.media-amazon.com/images/I/61eCzGg4AX...,4.5,"32,892 ratings",728

In [31]:
df_PC.to_csv("PC.csv" , index = False )
df_PC.to_parquet("PC.parquet" , index = False )